name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: get commit info
        run: echo "SHA=$GITHUB_SHA" >> $GITHUB_ENV

      - name: prepare release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: automated release at commit ${{ env.SHA }}
          draft: false
          prerelease: false

      - name: java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: '${{ runner.os }}-m2-${{ hashFiles(''**/pom.xml'') }}'
          restore-keys: '${{ runner.os }}-m2'

      - name: package
        run: mvn clean package --batch-mode --show-version --errors --file pom.xml

      - name: upload release asset
        uses: csexton/release-asset-action@v2
        with:
          pattern: "target/*-release.jar"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
